import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRef, useEffect, useState } from "react";
// import '../styles/navigation.scss'
import "bootstrap/dist/css/bootstrap.min.css";
import { Hello } from "./hello";

const Home = () => {
  const navi = ["Home", "About", "Blog"];

  const [navigation, setNavigation] = useState("Home");

  useEffect(() => {
    const window_height = window.innerHeight;
    navi.map((nav, index) => {
      if (nav === navigation) {
        console.log("nav1", navigation);
        window.scrollTo({
          top: window_height * index,
          behavior: "smooth",
        });
      }
    });
  }, [navi, navigation]);

  useEffect(() => {
    const setDotStatus = () => {
      const scroll_position = window.scrollY;
      const window_height = window.innerHeight;
      const half_window = window.innerHeight / 2;
      navi.map((nav, index) => {
        if (
          scroll_position > window_height * index - half_window &&
          scroll_position < window_height * index + half_window
        ) {
          console.log("nav2", navigation);
          setNavigation(nav);
        }
      });
    };
    window.addEventListener("scroll", setDotStatus);

    return () => window.removeEventListener("scroll", setDotStatus);
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>ST United</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hello />
      <main className="main">
        <div className="navigation">
          <ul id="js-dots">
            {navi.map((item, index) => (
              <li
                key={index}
                onClick={() => setNavigation(item)}
                className={navigation === item ? "active" : ""}
              >
                {item}
                <span></span>
              </li>
            ))}
          </ul>
        </div>
        <div className="row">
          <div className="col-lg-3"></div>
          <div className="col-lg-9">
            <section>
              <section className={styles.section}>
                <h2 className={styles.sectionHeading}>Scroll up and down</h2>
              </section>
              <section className={styles.section}>
                <h2 className={styles.sectionHeading}>Click on the nav dots</h2>
              </section>
              <section className={styles.section}>
                <h2 className={styles.sectionHeading}>Smooth scrolling</h2>
              </section>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
